module.exports = {
  HANDLE_TICKET_SORT: 'HANDLE_TICKET_SORT',
  CHANGE_BOARD_TITLE: 'CHANGE_BOARD_TITLE',
  ADD_ANOTHER_LIST: 'ADD_ANOTHER_LIST',
  DELETE_LIST: 'DELETE_LIST',
  CHANGE_TICKET_DETAILS: 'CHANGE_TICKET_DETAILS',
  ADD_NEW_CARD: 'ADD_NEW_CARD',
  DELETE_TICKET: 'DELETE_TICKET'
};
